#!/bin/bash

set -e

DATASET=${1%/}

echo "${DATASET} - preprocessing recordings"
ml-run-process ephys.bandpass_filter \
        --inputs timeseries:${DATASET}/raw.mda \
        --outputs timeseries_out:${DATASET}/filt.mda.prv \
        --parameters samplerate:30000 freq_min:300 freq_max:6000
ml-run-process ephys.whiten \
        --inputs timeseries:${DATASET}/filt.mda.prv \
        --outputs timeseries_out:${DATASET}/pre.mda.prv

echo "${DATASET} - sorting spikes"
ml-run-process ms4alg.sort \
        --inputs \
                timeseries:${DATASET}/pre.mda.prv geom:${DATASET}/geom.csv \
        --outputs \
                firings_out:${DATASET}/firings.mda \
        --parameters \
                detect_sign:1 \
                adjacency_radius:-1 \
                detect_threshold:3

echo "${DATASET} - computing templates"
ml-run-process ephys.compute_templates \
        --inputs timeseries:${DATASET}/raw.mda firings:${DATASET}/firings.mda \
        --outputs templates_out:${DATASET}/templates.mda.prv \
        --parameters clip_size:150

echo "${DATASET} - computing cluster metrics"
ml-run-process ephys.compute_cluster_metrics \
        --inputs timeseries:${DATASET}/pre.mda.prv firings:${DATASET}/firings.mda \
        --outputs metrics_out:${DATASET}/metrics.json \
        --parameters clip_size:150 samplerate:30000 refrac_msec:1.0
